services:
  - type: web
    name: hr-app-backend
    env: node
    buildCommand: npm install
    startCommand: npm run start:prod
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 8090
      - key: JWT_SECRET
        sync: false
      - key: JWT_EXPIRY_TIME
        value: 7d
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_KEY
        sync: false
      - key: FRONTEND_URL
        sync: false 